language: ruby
rbenv:
 - 2.4.1
services:
  - postgresql
before_script:
  - bundle exec rake db:{drop,create,migrate,seed}
addons: # get google-chrome-stable
  chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

script:
  - whereis google-chrome-stable
  - whereis chromedriver

before_install:
  - gem install bundler
  - gem install selenium-webdriver
  - gem install rake
